kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: k8s.io/nfs
parameters:
  mountOptions: "vers=4.1"  # TODO: reconcile with StorageClass.mountOptions
